version: '3.4'

services:
  website-manager:
    image: website-manager
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
