version: '3.4'

services:
  website-manager:
    image: website-manager
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
      - 9229:9229
    command: ["NODE_ENV=production","node", "--inspect=0.0.0.0:9229", "server.js"]
